amphp/http-server

lib/Vhost.php
Don't merge as long as H2 doesn't run without problems.
=> Activate H2 only when it's supported by the bundled OpenSSL version

lib/Vhost.php
1. `$name` of `__construct()` will always be a string, so the first branch of the ternary will always be taken.
2. The IF statement comparing that `$this->name` does not equal `null` will always take the first branch since `$this->name` will always be a string (due to the assignment on first line of method).
3. `date_default_timezone_get()` will always have a value, so no need to default it to UTC
=> Clean up buggy code

lib/VhostContainer.php
Minor variable case mixing causing PHP 7 to trigger an error: Undefined property
=> Fixes problem with 'Undefined property' in VhostContainer

lib/CommandClient.php
CommandClient::socketPath normalizes paths by replacing `/` and `:` with underscores. But Windows uses backslashes `\`.
This PR fixes it by als adding backslash to the search list.
=> Fixes filename normalizer on Windows

lib/Server.php
before it a string when result of parse_url() and a int when the
default was used.
=> Use always strings to represent the port

demo.php
I installed aerys using this guide http://blog.kelunik.com/2015/10/21/getting-started-with-aerys.html, but when running the demo application I got fatal errors because there is no longer a send() method on the StandardResponse class.
I have replaced the calls to send() with calls to end().
=> Fix demo.php: Replace 'send' method calls with 'end' method calls.

lib/Root.php
`Aerys\Root` sets the MIME type for HTTP responses by looking up the file extension of the requested file in the [mime file](https://github.com/amphp/aerys/blob/v0.4.3/etc/mime). However, when `Aerys\Root` parses the mime file, the regex used ignores MIME type suffixes. This means that for `.svg` files, Aerys response with a content type of `image/svg` instead of `image/svg+xml`, which prevents browsers from displaying `svg` files correctly. This PR addresses this issue.
=> Handle MIME types with suffixes correctly

lib/WatcherProcess.php
There must be possibility to adjust workers PHP arguments as well.
I propose following approach:
```
./aerys/vendor/bin/aerys -c ./aerys/server.php --worker-args="-n"
```
=> Add possibility to specify php options for workers

lib/Host.php, lib/Vhost.php, lib/VhostContainer.php, test/ClientTest.php, test/VhostTest.php, test/bootServerTest.php
An alternate solution for #124 (previous PR at #170):
You can now set a specific expected port the client must specify in the Host header or wildcard port ("*") to avoid any port matching there.
=> Fix #124 (the second)

bin/aerys-worker, lib/Host.php, lib/Server.php, lib/Vhost.php, lib/VhostContainer.php, lib/WatcherProcess.php, lib/WorkerProcess.php, test/HostTest.php, test/ServerTest.php, test/VhostTest.php, test/WatcherProcessTest.php
As noted in #168: it is necessary to always use socket transfer for Unix Domain Sockets, thus we need to decide ourselves in worker whether to use socket transfer or not.
Thus, unix domain sockets should generally be impossible with < PHP 7.0.7 and without sockets extension in production mode (i.e. when using multiple workers).
=> Unix Domain Socket support (PR for #168)

lib/Internal/functions.php, test/bootServerTest.php, test/testBootServerInclude.php
#188 Fix:
1.  If config is `\Generator` get its return value and continue following checks
2. Update `test/testBootServerInclude.php` to cover this case
3. Rename `BootstrapperTest` -> `bootServerTest` class
=> Fix generator promise return

lib/StandardRequest.php
E.g. it is valid to have a param like "foo=bar+baz" which should decode to "bar baz" which is not the case with rawurldecode
=> GET param values should be decoded with urldecode

lib/WatcherProcess.php
Everyone can log at the level he want in fact.
=> Remove log level recommandation log for production

lib/Server.php, test/ServerTest.php
In most web-servers and http-clients implementations header values joined with comma and space. 
I am fix it for `Allow` header in 2 places.
=> Join Allow header values with comma and space (according with RFC 7231)

lib/WatcherProcess.php
This avoids to have to install nproc for Linux (eg when running aery into a lightweight/minimal docker image). It's also the most portable approach for *NIX systems BTW.
=> Adopt a more portable cpu detection

docs/README.md, docs/_config.yml, docs/classes/index.md, docs/classes/message.md, docs/classes/request-body.md, docs/classes/request-handler.md, docs/classes/request.md, src/Request.php
PR for #242:
1. Updated Jekyll config (`gems` -> `plugins`)
2. Updated `docs/README.md`: `git submodule` explanation added
3. Removed links to missing classes in `docs/classes/index.md`
4. Added stubs for new `docs/classes/message.md`, `docs/classes/requestbody.md` and `docs/classes/requesthandler.md`
5. Updated `docs/classes/request.md`
6. Changed the order of setter and getter of HTTP method (to keep it consistent)
=> Request documentation update

src/Request.php, src/Response.php, test/RequestTest.php, test/ResponseTest.php, test/TrailersTest.php
Two separate methods would really have been cleaner, as that would have allowed people to use strict types if they prefer.
=> Convert convertible types to string on setBody()

src/Server.php
Using compression defaults to true in Options which can lead to an `Undefined constant ZLIB_ENCODING_GZIP` error on a php built without zlib.
This check prevents the compression middleware to be added to the stack on these systems while advising user to install zlib.
=> Log error if zlib is disabled

src/Server.php
`$clientFactory` will never have a value. Perhaps it used to be a constructor argument, or this line was copied from elsewhere.
=> Remove redundant check

src/Driver/Http2Driver.php, src/Options.php, test/Driver/Http2DriverTest.php, test/OptionsTest.php
Dropping arbitrary average frame size in favor of nginx-inspired flood protection based on the number of payload (header or data) frames received vs. the overall number of bytes received, including frame headers. This protects against both control frame floods and tiny data frame floods.
=> Refactor flood prevention

src/Driver/Http1Driver.php, test/Driver/Http1DriverTest.php
The current implementation of chunk parsing can break in specific combinations of HTTP chunk-size and options::$chunkSize.
I added a test-data provider which runs the chunk test with chunk-sizes from 1 to 10 against the example HTTP request with chunks in size 4 and 5. This breaks without the fix to `Http1Driver`.
I also had to edit `composer.json` to make sure PHPUnit does not upgrade to v8 as this is incompatible with the listener configuration in `phpunit.xml.dist`. I considered it out of the scope of this MR to fix the deprecated listener config.
=> Fix bug related to HTTP content chunking

src/Driver/RemoteClient.php, src/Middleware/ExceptionMiddleware.php
I had a problem that my monolog handlers were not logging exceptions correctly. It is because they expect the exception to be in the context.
=> Improve exception logging

composer.json
The file only contains a `class_alias` to `HttpServer` which is not picked up in `--classmap-authoritative` composer-autoloaders. Adding it to the autoload-files list fixes this. 
Fixes #319
=> Load `src/Server.php` as file-autoload

examples/delayed-response.php, examples/exception.php, examples/hello-world.php, examples/state.php, examples/stream.php, src/Driver/Http1Driver.php, src/Driver/Http2Driver.php, src/Driver/RemoteClient.php, src/Driver/UpgradedSocket.php, src/HttpServer.php, src/Middleware/CompressionMiddleware.php, src/Request.php, src/Response.php, test/Driver/Http1DriverTest.php, test/Driver/Http2DriverTest.php, test/Driver/RemoteClientTest.php, test/RequestBodyTest.php, test/RequestTest.php, test/ResponseTest.php, test/ServerTest.php, test/test-server.php
Made a few broad fixes on the v3 branch that get the examples running and most of the tests passing:
* `Socket\Server::listen` => `Socket\listen` as per https://github.com/amphp/socket/commit/88b0e8dee4d9eece2fd53deb6bcb088fa636a416
* `PipelineStream(new AsyncGenerator` => `IterableStream` as per https://github.com/amphp/pipeline/releases/tag/v1.0.0-beta.2 (not 100% sure if I did this right but it seems to work)
* `EmmitterStream::asPipeline()` `EmmitterStream::pipe()`
* `InMemoryStream` => `ReadableBuffer` as per https://github.com/amphp/byte-stream/releases/tag/v2.0.0-beta.1
=> Fixes on v3

src/Internal/PerformanceRecommender.php
Fixes a minor typo of not having a space between two words due to concatination.
```diff
-Enable assertions in php.ini (zend.assertions = 1) to enabledebug logging.
+Enable assertions in php.ini (zend.assertions = 1) to enable debug logging.
```
=> Fix typo in performance recommendation

src/Middleware/CompressionMiddleware.php
Regarding [this issue](https://github.com/amphp/http-server/issues/324), the merged change added a constructor parameter to the CompressionMiddleware, but did not set the corresponding property in the constructor. This PR rectifies that.
=> Fix setting buffer timeout in CompressionMiddleware
