lib/Bootstrapper.php, lib/DebugProcess.php, lib/WorkerProcess.php, test/BootstrapperTest.php
This allows fetching e.g. configuration and building hosts based on it.
=> Allow async I/O in config files

lib/InternalRequest.php
=> added phpdocs to InternalRequest

lib/Bootable.php, lib/Bootstrapper.php, lib/DebugProcess.php, lib/Process.php, lib/Router.php, lib/Server.php, lib/Ticker.php, lib/WatcherProcess.php, lib/Websocket/Rfc6455Endpoint.php, lib/WorkerProcess.php, lib/functions.php, test/TestBootstrapperInclude.php, test/WebsocketParserTest.php
See https://github.com/amphp/aerys/issues/96
=> Server now declares Psr\Log\LoggerInterface instead of concrete class

lib/Logger.php
Pretty self explanatory. Would like to get the full datetime for log entries.
=> Include full DateTime for Logger

lib/Server.php
as per method signature:
`private function tryApplication(InternalRequest $ireq, callable $application, array $filters)`
=> added missing argument

lib/StandardResponse.php, test/ServerTest.php, test/StandardResponseTest.php
=> Add default reason phrase if none is set

lib/CommandClient.php, lib/IpcLogger.php, lib/WatcherProcess.php, lib/WorkerProcess.php, test/CommandClientTest.php, test/WatcherProcessTest.php
=> Move socket transfer to CommandClient

demo.php, docs/classes/router.md, docs/http-advanced.md, docs/http.md, lib/Router.php, test/RouterTest.php
=> Remove magic __call from Router

lib/Internal/functions.php
=> Throw descriptive error if no hosts are returned from the config file

bin/aerys, lib/Internal/functions.php
=> Add command-line option --user -u for setting the user to switch to

lib/Server.php
=> Fix waiting for pending responses on shutdown

src/Message.php, test/TrailersTest.php
Fixes #224 with TrailersTest testing this method.
=> Add hasHeader() method to Message

src/Message.php, test/TrailersTest.php
=> Prevent empty header arrays

src/Request.php, test/RequestTest.php
=> Add Request::setMethod()

README.md
Add contributing sections to README #238
=> Update readme.md: add Contributing sections

docs/classes/request.md, src/Request.php, src/Response.php, test/RequestTest.php
Small doc updates that were requested in PR #245
=> Update classes/request docs

docs/classes/response.md, src/Response.php
#226 Documentation update for `Response` class
=> Update Response docs

docs/classes/options.md, src/Options.php
#226 Documentation update for `Options`
=> Update Options docs

docs/production.md
=> Update production docs

docs/classes/server.md, src/Server.php
=> Server class docs

composer.json
Infection has had a lot of improvements since 0.7
* [0.8 post](https://infection.github.io/2018/02/28/whats-new-in-0-8-0/)
* [0.9 post](https://infection.github.io/2018/07/01/whats-new-in-0.9.0/)
=> Update infection to 0.9 version

README.md, docs/addons.md
As requested [here](https://github.com/amphp/http-server/issues/303#issuecomment-594734312).
=> Add CORS links

README.md, docs/addons.md, docs/classes/request-body.md
=> Add links to amphp/http-server-form-parser in docs

docs/index.md, src/Driver/RemoteClient.php, src/Middleware/ExceptionMiddleware.php, src/Options.php
=> Pass Request to Logger

src/Internal/PerformanceRecommender.php
=> Fied typo in performance recommender

src/HttpServer.php
=> Remove useless phpdoc tags

src/HttpServer.php
Closes #338. @cspray and @kelunik what do you think?
=> Add HttpServerSupervisor interface
